# Generated by Django 5.2.5 on 2025-08-17 21:53

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='مرحبا أنا', max_length=50, verbose_name='التحية')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[500, 500], upload_to='profile_images/', verbose_name='الصورة الشخصية')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='تويتر')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='جيت هاب')),
                ('dribbble_url', models.URLField(blank=True, null=True, verbose_name='دریبل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوى الصفحة الرئيسية',
                'verbose_name_plural': 'محتوى الصفحة الرئيسية',
            },
        ),
    ]
