# Generated by Django 5.2.5 on 2025-08-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عني', max_length=100, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('cv_url', models.URLField(verbose_name='رابط السيرة الذاتية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'قسم عني',
                'verbose_name_plural': 'قسم عني',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200, verbose_name='المعهد/الجامعة')),
                ('degree', models.CharField(max_length=200, verbose_name='الدرجة العلمية')),
                ('period', models.CharField(max_length=50, verbose_name='الفترة الزمنية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'تعليم',
                'verbose_name_plural': 'التعليم',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='الشركة')),
                ('position', models.CharField(max_length=200, verbose_name='المنصب')),
                ('period', models.CharField(max_length=50, verbose_name='الفترة الزمنية')),
                ('responsibilities', models.TextField(verbose_name='المسؤوليات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'خبرة عمل',
                'verbose_name_plural': 'خبرات العمل',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='الأيقونة')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المهارة')),
                ('percentage', models.IntegerField(verbose_name='النسبة المئوية')),
                ('skill_type', models.CharField(choices=[('tech', 'مهارات تقنية'), ('pro', 'مهارات احترافية')], max_length=10, verbose_name='نوع المهارة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'مهارة',
                'verbose_name_plural': 'المهارات',
            },
        ),
    ]
