# Generated by Django 5.2.5 on 2025-08-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutsection_education_experience_service_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order'], 'verbose_name': 'تعليم', 'verbose_name_plural': 'التعليم'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name': 'خبرة عمل', 'verbose_name_plural': 'خبرات العمل'},
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(help_text='أدخل كل مسؤولية في سطر جديد', verbose_name='المسؤوليات'),
        ),
    ]
