# Generated by Django 5.2.5 on 2025-08-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('full_time', 'العمل بدوام كامل'), ('fixed', 'مشروع سعر ثابت'), ('hourly', 'العمل كل ساعة')], max_length=20, verbose_name='نوع الخطة')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الخطة')),
                ('description', models.TextField(verbose_name='وصف الخطة')),
                ('price', models.CharField(max_length=50, verbose_name='السعر')),
                ('features', models.TextField(help_text='أدخل كل ميزة في سطر جديد', verbose_name='الميزات')),
                ('button_text', models.CharField(default='وظفني', max_length=50, verbose_name='نص الزر')),
                ('button_url', models.URLField(default='#', verbose_name='رابط الزر')),
                ('icon', models.CharField(help_text='استخدم أسماء أيقونات FontAwesome مثل: fa-calendar', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خطة تسعير',
                'verbose_name_plural': 'خطط التسعير',
                'ordering': ['order'],
            },
        ),
    ]
