# Generated by Django 5.2.5 on 2025-08-18 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pricingplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المنشور')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='رابط المنشور')),
                ('content', models.TextField(verbose_name='محتوى المنشور')),
                ('excerpt', models.TextField(max_length=300, verbose_name='ملخص المنشور')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='صورة الغلاف')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'منشور المدونة',
                'verbose_name_plural': 'منشورات المدونة',
                'ordering': ['-publish_date'],
            },
        ),
    ]
