# Generated by Django 5.2.5 on 2025-08-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='رابط التصنيف')),
                ('filter_class', models.CharField(help_text='استخدم نفس القيمة المستخدمة في القالب (مثال: user-interface, branding)', max_length=50, verbose_name='فئة التصفية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف المحفظة',
                'verbose_name_plural': 'تصنيفات المحفظة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='رابط المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('short_description', models.CharField(max_length=200, verbose_name='وصف مختصر')),
                ('main_image', models.ImageField(upload_to='portfolio/main/', verbose_name='الصورة الرئيسية')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='رابط المشروع')),
                ('technologies', models.TextField(blank=True, help_text='أدخل كل تقنية في سطر جديد', verbose_name='التقنيات المستخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='main.portfoliocategory', verbose_name='التصنيفات')),
            ],
            options={
                'verbose_name': 'عنصر المحفظة',
                'verbose_name_plural': 'عناصر المحفظة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name='صورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.portfolioitem')),
            ],
            options={
                'verbose_name': 'صورة المحفظة',
                'verbose_name_plural': 'صور المحفظة',
                'ordering': ['order'],
            },
        ),
    ]
