# Generated by Django 5.2.5 on 2025-08-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_portfoliocategory_portfolioitem_portfolioimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد إلكتروني إضافي')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف إضافي')),
                ('map_embed_code', models.TextField(blank=True, help_text='أدخل كود iframe للخريطة من Google Maps', null=True, verbose_name='كود الخريطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'معلومات الاتصال',
                'verbose_name_plural': 'معلومات الاتصال',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('read', 'تم القراءة'), ('replied', 'تم الرد'), ('archived', 'مؤرشف')], default='new', max_length=10, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
